version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: productmgmt-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user1233
      MYSQL_DATABASE: product_mgmt
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: productmgmt-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productmgmt-app
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_mgmt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: user1233
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
